Select DISTINCT CITY
FROM STATION 
WHERE (LEFT(CITY, 1) = 'A'|| LEFT(CITY,1)='E'||LEFT(CITY,1)='I'||LEFT(CITY,1)='O'||LEFT(CITY,1)='U')&& (RIGHT(CITY, 1) = 'A'|| RIGHT(CITY,1)='E'||RIGHT(CITY,1)='I'||RIGHT(CITY,1)='O'||RIGHT(CITY,1)='U');